version: '3'
services:

  # Configures our video-streaming microservice
  video-streaming:
    # Sets the name of the image 
    image: video-streaming
    build: 
      # directory for the microservice
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
     - "4000:80"
    environment:
      - PORT=80
    restart: "no"